name: mqcn
channels:
  - conda-forge
  - defaults
dependencies:
  - fitsio
  - _ipyw_jlab_nb_ext_conf
  - alabaster
  - anaconda
  - anaconda-client
  - anaconda-project
  - asn1crypto
  - astroid
  - astropy
  - atomicwrites
  - attrs
  - babel
  - backcall
  - backports
  - backports.os
  - backports.shutil_get_terminal_size
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blas
  - blaze
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - cmake
  - colorama
  - conda-verify
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - datashape
  - dbus
  - decorator
  - defusedxml
  - distributed
  - docutils
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - filelock
  - flask
  - flask-cors
  - fontconfig
  - freetype
  - fribidi
  - future
  - get_terminal_size
  - gevent
  - glib
  - glob2
  - gmp
  - gmpy2
  - graphite2
  - greenlet
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - imagesize
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jdcal
  - jedi
  - jeepney
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - libarchive
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - liblief
  - libpng
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multipledispatch
  - navigator-updater
  - nbconvert
  - nbformat
  - ncurses
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - odo
  - olefile
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - partd
  - patchelf
  - path.py
  - pathlib2
  - patsy
  - pcre
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkginfo
  - pluggy
  - ply
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - py
  - py-lief
  - pycodestyle
  - pycosat
  - pycparser
  - pycrypto
  - pycurl
  - pyflakes
  - pygments
  - pylint
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytables
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python=3.6
  - python-dateutil
  - python-libarchive-c
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtawesome
  - qtconsole
  - readline
  - requests
  - rhash
  - rope
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - secretstorage
  - send2trash
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snappy
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tblib
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - unicodecsv
  - unixodbc
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xlrd
  - xlsxwriter
  - xlwt
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - zstd
  - pip:
    - aplpy
    - flake8
    - libarchive-c
    - lief
    - msgpack
    - pyqt5
    - qtpy
    - tables
