#!/usr/bin/env python
""" Utility script to reduce filesize of FITS spectra
"""
import pipeline as io
from glob import glob
import argparse

parser = argparse.ArgumentParser(description='Remove unnecessary data from FITS files')

parser.add_argument('parent', type=str,
                    help='Parent directory containing the full size FITS files')

args = parser.parse_args()
parent = args.parent.strip('/')
filelist = glob('{:s}/*.fits'.format(parent))

for filename in filelist:
    io.shrink_spectra(filename)
    
print('Done with {} files'.format(len(filelist)))
print('Now you can remove {}'.format(parent))